### PR TITLE
version 0.8.0

### PR DESCRIPTION
**Pull request by kenji123**
New version adds XMLTV, multi-portal and authentication features. Plus various fixes and improvements.

### CODE REVIEW

**Comment by hudokkow** [comment]
Holy s**t! This is unreviewable. Can you please squash commits in logical chunks?

**Comment by kenji123** [comment]
Is this better? I can try to squash it some more if need be.

**Comment by hudokkow** [comment]
Much better, thanks. Will review and let you know.

**Comment by hudokkow** [comment]
@kenji123, please rebase so I can merge tonight.

**Comment by MartijnKaijser** [comment]
see it's rebased

**Comment by Jalle19** [comment]
@hudokkow did you finish the review?

**Comment by hudokkow** [comment]
Sorry for the noise. Didn't noticed https://github.com/kenji123/pvr.stalker/commit/009988368b2737003716afc0263aa2c84821dfd9

**Pull request merged**
