### PR TITLE
Fix UWP build: isolates libxml2 version

### PR DESCRIPTION
**Pull request by thexai**
Previous PR has fixed libxml2 version (2.9.10) correctly reported on package config but unfortunately does not fix main problem: 

libxml2 are not build in UWP if previous build exists (file `xml2.lib` file exists but with different build flags).

This PR isolates 2.9.10 version including version number in source folder and build folder names --> `libxml2-2.9.10`

This ensures that it will be rebuild again because it does not exist.

Also simplified specific Windows CMakeLists.txt removing non Windows options.

Tested careful: tested build locally only pvr.stalker addon and all addons in batch. Doesn't seem like it can fail now in Jenkins...

### CODE REVIEW

**Comment by fuzzard** [comment]
I'll just comment on something you've pretty much run into.

I poked at the addon cmake system a few days ago, and theres BIG issues with it pulling in lib locations from core, which is exactly why you're having this issue.

Im not fussed if you work around it in this instance, but i'll tell you theres absolutely going to be similar issues for any addon that has a similar dependency to core in any way. It really has to be fixed in the addon cmake build system, but i dont want to really dig into that at this point in time.

**Comment by thexai** [comment]
I agree, it's a core problem but I don't have the necessary CMake knowledge to fix it.

This fixes this particular addon and there are 2 or 3 others with patch.exe related issues (it will be fixed with https://github.com/xbmc/xbmc/pull/21377).

All other addons compile fine on UWP.

**Comment by fuzzard** [comment]
Yeah, by all means my comment wasnt a yay/nay for this PR, just thought id make public that our addon build system can/will have issues with libs that core uses, as it will include core lib includes

**Comment by thexai** [comment]
ping @phunkyfish

**Comment by phunkyfish** [comment]
Do you need a new release build for this?

If so you will need to bump the version number (just the micro number in addon.xml.in) and add a changelog entry.

**Comment by thexai** [comment]
In theory there is no functional change in the addon or even in the code. It only makes it compile under certain conditions. But I can increase the version if you prefer.

**Comment by phunkyfish** [comment]
If you don’t require a release build then let’s leave it as is.

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
