### PR TITLE
[Nexus] update libxml2 on depends to 2.9.10

### PR DESCRIPTION
**Pull request by AlwinEsch**
This should also fix faulty Windows UWP builds:
```
xml2.lib(encoding.c.obj) : error LNK2001: unresolved external symbol iconv_close
xml2.lib(encoding.c.obj) : error LNK2001: unresolved external symbol iconv
xml2.lib(encoding.c.obj) : error LNK2001: unresolved external symbol iconv_open
xml2.lib(xmlreader.c.obj) : error LNK2001: unresolved external symbol xmlValidatePopElement
pvr.stalker.dll : fatal error LNK1120: 4 unresolved externals
```

**WARNING:** This need be tested to confirm correct operations about add-on!

### CODE REVIEW

**Comment by ksooo** [comment]
>  AlwinEsch requested a review from ksooo

Sorry, cannot review as I have no clue about our build system and I cannot test as I have no suitable hardware.

**Comment by phunkyfish** [comment]
Windows appears to still be failing.

**Comment by AlwinEsch** [comment]
With the Version 2.9.10 becomed it now working. 
To use newest and his own cmake makes some Problems on Windows, thats why I used 2.9.10 now and taken CMakeLists.txt from inputstream.ffmpegdirect with few changes on compile flags.

**Review by phunkyfish — APPROVED** [review]

**Comment by ksooo** [comment]
@AlwinEsch is a backport to Matrix feasible or is this problem Nexus-only?

**Comment by ksooo** [comment]
> is a backport to Matrix feasible or is this problem Nexus-only?

Answering my own question. Yes, there already is a PR for thsis. ;-)

**Pull request merged**
