### PR TITLE
add debian packaging

### PR DESCRIPTION
**Pull request by notspiff**

### CODE REVIEW

**Comment by hudokkow** [comment]
Thanks @notspiff. Waiting on @kenji123 response.

**Comment by kenji123** [comment]
Yes @hudokkow.

**Comment by hudokkow** [comment]
OK, yes but what? See https://github.com/kodi-pvr/pvr.vbox/blob/master/debian/copyright for an example.

**Comment by kenji123** [comment]
Copyright: 2015 Jamal Edey <jeanstarwin@gmail.com>
License: GPL-2+

**Pull request merged**
