### PR TITLE
fixes and cleanup

### PR DESCRIPTION
**Pull request by kenji123**
A coverity fix, and a bit of refactoring and cleaning up

### CODE REVIEW

**Comment by Jalle19** [comment]
Can you update the addon version while you're at it? We had a brief discussion about addon versions and came to the conclusion that everyone should bump the major version when the targeted Kodi version changes. So this one should change from `0.9.7` to either `1.0.0` or `1.9.7`(I personally prefer the latter).

**Comment by hudokkow** [comment]
@kenji123, there are 6 more Coverity CIDs to fix. All of them look like

>CID 105655 (#1 of 1): Resource leak (RESOURCE_LEAK)7. overwrite_var: Overwriting header in header = NULL leaks the storage that header points to

Mind having a look? Thanks.

**Comment by kenji123** [comment]
@Jalle19, there's another pr I plan to do soon. So, I'll bump the version then. `1.0.0` makes more sense to me. Why do you prefer `1.9.7`?

@hudokkow, ok.

**Comment by hudokkow** [comment]
@kenji123, we're going to branch for Jarvis in a few days.
If you don't have time to finish your other PR, please include an addon bump and changelog update. It should be the very first PR to go in *after* branching.

That is, unless you want this to go in before branching. In that case bump the addon and we can bump it to 1.0.0 in master branch only after branching. Your call.

**Comment by kenji123** [comment]
@hudokkow, the other PR, along with a version bump and changelog update is done. I intend have both merged before early tomorrow.

**Pull request merged**
